variables:
  MajorVersion: 1
  MinorVersion: 0
  Patch: 0
  MainProject: 'Operational.Judith'
  Port: 6001
  UseGateway: 'Yes'
  AWSResourceName: 'operational-judith'
  healthcheck: "/.well-known/apollo/server-health"

name: $(MajorVersion).$(MinorVersion).$(Patch)-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
  paths:
    include:
    - src/*
    - azure-pipelines.yml

resources:
  repositories:
  - repository: templates
    type: git
    name: DevOps/templates
    ref: refs/heads/master

stages:
  - template: stages/build/NodeWithDocker.yaml@templates
    parameters:
      projectName: $(MainProject)
      majorVersion: $(MajorVersion)
      minorVersion: $(MinorVersion)
      patch: $(Patch)
  - template: stages/release/AWS/ECRAndCloudFormation.yaml@templates
    parameters:
      additionalParameters:
        dependsOn: Build
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'master'))
      projectName: $(MainProject)
      file: 'Templates/Towner/API.json'
      deployParameters:
        Parameter_Port: $(Port)
        Parameter_UseGateway: $(UseGateway)
        Parameter_Name: $(AWSResourceName)
        Parameter_ContainerHealthCheck: $(healthcheck)
        Parameter_LoadBalanceHealthCheck: $(healthcheck)
